
# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: 
    - "udlvb/css/"
    - "udlvb/js/"
    - "udlvb/img/"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/udlvb.js"